### ISSUE TITLE
May I ask which paper this equation from?

### ISSUE THREAD

**Issue by Hd-Edison** [Leoopessoa/MMI-Multi-Mode-Interferometer-2x2#2]
May I ask which paper this equation from? Thank you
W_wg = (1/((2*n)**(1/4)))*np.sqrt(lambda0*We/neffapx[0])

**Comment by Leoopessoa** [comment]
Hello, Jia Tao, sorry for the delay in responding . I searched in some papers i have and couldn't find it. Did you found it somewhere or still searching for ? 

My appologies, 

Leonardo Pessôa.

**Comment by Hd-Edison** [comment]
Hello, Leonardo, I have given up in looking for it in papers and have used it in my code anyway. I'll let you know if i see it in other papers. And thanks again for your help.


Jia Tao.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 上午8:30
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Leoopessoa/MMI-Multi-Mode-Interferometer-2x2] May I ask which paper this equation from? (Issue #2)





 
Hello, Jia Tao, sorry for the delay in responding . I searched in some papers i have and couldn't find it. Did you found it somewhere or still searching for ?
 
My appologies,
 
Leonardo Pessôa.
